---
apiVersion: v1
kind: Service
metadata:
  name: portainer-lb
  namespace: portainer
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: portainer
  ports:
    - name: https
      protocol: TCP
      port: 9090s
      targetPort: 9000
  type: LoadBalancer
